name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - "**.lua"
      - .github/workflows/ci.yml
      - "README.md"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          ignore: "DL3008,DL3013,SC2015"
          verbose: true
      - name: Lint Markdown files
        uses: actionshub/markdownlint@main
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          check_hidden: true
          ignore_words_list: noice
